name = "ITPM_SimX"
uuid = "c9f5d8ff-7668-42f6-b4bd-33d959564478"
authors = ["V1talyK"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
